services:
  ai-service:
    build: ./ai-service
    ports:
      - "8010:8000"

  parser-service:
    build: ./parser-service
    ports:
      - "8011:8001"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8012:8002"
    depends_on:
      - ai-service
      - parser-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9080:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3010:3000"
